import {Transaction} from '../types';
import {transactionIcon} from './images';

export const events = [
  {
    id: '1',
    name: 'Lonavala',
    amount: 3000,
  },
  {
    id: '2',
    name: 'Pratham Visit',
    amount: 6000,
  },
  {
    id: '3',
    name: 'Pune Travel',
    amount: 3000,
  },
  {
    id: '4',
    name: 'Ghar Groceries',
    amount: 3000,
  },
];

export const transactions: Transaction[] = [
  {
    id: '1',
    name: 'Flight Booking',
    date: 'Today',
    amount: 850,
    type: 'travel',
    transactionType: 'transaction',
    description: 'Flight to New York',
  },
  {
    id: '2',
    name: 'Grocery Shopping',
    date: 'Yesterday',
    amount: -85,
    type: 'necessity',
    transactionType: 'transaction',
    description: 'Weekly groceries at the supermarket',
  },
  {
    id: '3',
    name: 'Dining Out',
    date: 'Jan 30, 2022',
    amount: 1406,
    type: 'food',
    transactionType: 'transaction',
    description: 'Dinner at a fancy restaurant',
  },
  {
    id: '4',
    name: 'Netflix Subscription',
    date: 'Jan 16, 2022',
    amount: -11.99,
    type: 'entertainment',
    transactionType: 'monthly payment',
    description: 'Monthly Netflix subscription fee',
  },
  {
    id: '5',
    name: 'Luxury Watch',
    date: 'Jan 16, 2022',
    amount: -2999.99,
    type: 'luxury',
    transactionType: 'transaction',
    description: 'Purchase of a luxury wristwatch',
  },
  {
    id: '6',
    name: 'Massage Therapy',
    date: 'Jan 16, 2022',
    amount: -150,
    type: 'comfort',
    transactionType: 'transaction',
    description: 'Spa massage therapy session',
  },
  {
    id: '7',
    name: 'Freelance Payment',
    date: 'Jan 16, 2022',
    amount: 30000,
    type: 'comfort',
    transactionType: 'income',
    description: 'Payment for completed freelance project',
  },
];


export const Bills: Transaction[] = [
  {
    id: '1',
    name: 'Rent',
    date: 'Today',
    amount: -9850,
    type: 'necessity',
    transactionType: 'transaction',
    description: 'Flight to New York',
  },
  {
    id: '2',
    name: 'Grocery Shopping',
    date: 'Yesterday',
    amount: -85,
    type: 'necessity',
    transactionType: 'transaction',
    description: 'Weekly groceries at the supermarket',
  },
  {
    id: '3',
    name: 'Dining Out',
    date: 'Jan 30, 2022',
    amount: 1406,
    type: 'food',
    transactionType: 'transaction',
    description: 'Dinner at a fancy restaurant',
  },
  {
    id: '4',
    name: 'Netflix Subscription',
    date: 'Jan 16, 2022',
    amount: -11.99,
    type: 'entertainment',
    transactionType: 'monthly payment',
    description: 'Monthly Netflix subscription fee',
  },
  {
    id: '5',
    name: 'Luxury Watch',
    date: 'Jan 16, 2022',
    amount: -2999.99,
    type: 'luxury',
    transactionType: 'transaction',
    description: 'Purchase of a luxury wristwatch',
  },
  {
    id: '6',
    name: 'Massage Therapy',
    date: 'Jan 16, 2022',
    amount: -150,
    type: 'comfort',
    transactionType: 'transaction',
    description: 'Spa massage therapy session',
  },
  {
    id: '7',
    name: 'Freelance Payment',
    date: 'Jan 16, 2022',
    amount: 30000,
    type: 'comfort',
    transactionType: 'income',
    description: 'Payment for completed freelance project',
  },
];
