export {default as bg} from '../../assets/bg3.png';
export {default as transactionIcon} from '../../assets/transaction.png';
export {default as pieChart} from '../../assets/piechart.png';
export {default as travel} from '../../assets/travel.png';
export {default as necessity} from '../../assets/necessity.png';
export {default as comfort} from '../../assets/comfort.png';
export {default as luxury} from '../../assets/luxury.png';
export {default as food} from '../../assets/food.png';
export {default as entertainment} from "../../assets/entertainment.png";
